sudo: required

services:
  - docker

before_install:
  - docker build -t puteulanus/ror2ds .
  - UPDATE_TIME=$(docker run -it puteulanus/ror2ds cat /root/RoR2DS/steamapps/appmanifest_1180760.acf | grep 'LastUpdated' | awk -F '"' '{print $(NF-1)}')
  - VER=$(date -d @$UPDATE_TIME +'%Y-%m-%d')
  - docker tag puteulanus/ror2ds puteulanus/ror2ds:$VER

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push puteulanus/ror2ds
  - docker push puteulanus/ror2ds:$VER
